### ISSUE TITLE
Display returned values in GW?

### ISSUE THREAD

**Issue by manaesh** [JRascagneres/HA-NationalGrid#5]
Great integration :)

Is there any configuration options or anyway to display the values in GWh?

Thanks

Mike

**Comment by JRascagneres** [comment]
@manaesh Hi. Thats not something I'm really willing to do as I'd have to duplicate the sensors. If you really want this you can make your own template sensors doing something like the following:

```
  - sensor:
    - name: "Nuclear GW"
      state_class: measurement
      unit_of_measurement: GW
      icon: mdi:turbine
      state: "{{states('sensor.national_grid_grid_generation_nuclear_mwh') | float(0) / 1000}}"
      ```
